### PR TITLE
Vep 86 + GGD recipes

### PR DESCRIPTION
**Pull request by matthdsm**
Added GGD recipes as mentioned in  bcbio-nextgen issue #1653
Bumped vep version to v86

I already prepared this, but I don't think it should be merged until there's been decided which further steps need to be taken to update VEP the right way.

M

### CODE REVIEW

**Comment by matthdsm** [comment]
tested code in dbscSNV recipes, preparation and tabix index works without issues for both builds

**Comment by chapmanb** [comment]
Thanks much for all this work. I'd be happy to merge this with a couple of changes/questions:

- Do we need to bump to VEP 86 now for this to work? Ideally I'd do that in combination with a 1.0.1 release. We can do a release soonish but I don't like forcing larger data upgrades for anyone in the middle of a development release upgrade.
- You extract the README file for dbNSFP and mention that VEP needs it but it doesn't get moved out of the transactional directory so will be extracted and deleted. Do you know how VEP requires it to be present to work? Any pointers at the dependency would be very helpful to understand what happens with it.

Thanks again for this.

**Comment by matthdsm** [comment]
Hi, 
- No, I don't suppose VEP_86 is absolutely necessary for this. The conda recipe for v86 however holds the needed perl modules for the extra plugins. I agree this can wait untill the next release (also looking forward to the new Freebayes version)
- Do I need to add the README file to the `repice_outfiles` then? The plugin just looks in the same directory as the dbnsfp file to find the readme. It isn't absolutely necessary, but it's nice to have a more complete header, and this info also gets included into the gemini db.
excerpt from de dbNSFP plugin:
```
sub get_header_info {
  my $self = shift;

  if(!exists($self->{_header_info})) {

    # look for readme
    my $file_dir = $self->{file};

    my %rm_descs;

    # won't work for remote
    if($file_dir !~ /tp\:\/\//) {

      # get just dir
      $file_dir =~ s/\/[^\/]+$/\//;

      if(opendir DIR, $file_dir) {
        my ($readme_file) = grep {/dbnsfp.*readme/i} readdir DIR;
        closedir DIR;

        if(open RM, $file_dir.$readme_file) {
          my ($col, $reading);
         .........
```

So if I modify the GGD recipe like this:
```
    recipe_outfiles:
      - variation/dbNSFP.txt.gz
      - variation/dbNSFP.txt.gz.tbi
      - variation/dbNSFP.readme.txt
```

I suppose it should work.

M

**Comment by matthdsm** [comment]
I'll revert the change to vep_86 back to 83
How does your versioning work of dbNSFP? I see as version name it's `3.1a2`.
Is this because it's modified? Is it allright if I use 3.1a as version for hg38 then?

M

**Comment by chapmanb** [comment]
Brilliant, thanks for fixing those things up. The versioning looks great to me. I had to bump the dbNSFP one because the original one would work but was incorrect, so folks needed to get a new version to actually have everything working. Thanks again for all the work on these, much appreciated.

**Comment by matthdsm** [comment]
So in it's current form the dbNSFP version for hg38 is set to 3.1a and for GRCh37 it's set to 3.1a2.
Wouldn't it be better to have the same version number for both genome builds? Or am I misunderstanding something?

**Comment by chapmanb** [comment]
There is no reason they need to be synchronized, the installs are completely independent. The point of the `3.1a2` for GRCh37 is that there was already a `3.1a` recipe that was broken so anyone who installed that needs to get the update. For hg38 we didn't have that so no need to have the more confusing version number.

**Comment by matthdsm** [comment]
alrighty then!

**Pull request merged**
