### PR TITLE
Add Conda packages Bismark and Trim Galore

### PR DESCRIPTION
**Pull request by hackdna**
Required by WGBS seq pipeline in bcbio (https://github.com/bcbio/bcbio-nextgen/tree/wgbs-seq)

### CODE REVIEW

**Comment by naumenko-sa** [comment]
TrimGalore is perl:
https://github.com/FelixKrueger/TrimGalore/blob/master/trim_galore

**Comment by roryk** [comment]
Yup, but it's a wrapper around cutadapt which I think doesn't support python3.

**Comment by hackdna** [comment]
Yes, it's a Perl wrapper script around FastQC (Java) and Cutadapt ([Python>=3.4](https://github.com/marcelm/cutadapt/blob/master/setup.py#L109))

**Comment by roryk** [comment]
Oh! cutadapt supports python3 now, got it.

**Pull request merged**
